### ISSUE TITLE
Suggestion for Documentation

### ISSUE THREAD

**Issue by katzberc** [jandiorio/study_group_screen#8]
I'm using the Ansible Student VM and I needed these instructions in order to complete your exercise.  https://gist.github.com/joelwking/7fc4231a8d762c95738cb1425695a404

**Comment by jandiorio** [comment]
@katzberc Thanks for the input.  We will look to include the use of our Programmability Foundations Lab as the development environment in our next run of the groups.  This was a result of the work you and Joel King did.
